version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=quiz_citologia
      - MYSQL_ROOT_PASSWORD=root
